DROP TABLE cash_closures              CASCADE;
DROP TABLE invoices                   CASCADE;
DROP TABLE invoices_products_products CASCADE;
DROP TABLE invoices_tickets_tickets   CASCADE;
DROP TABLE products                   CASCADE;
DROP TABLE services                   CASCADE;
DROP TABLE tickets                    CASCADE;
DROP TABLE customers                  CASCADE;
DROP TABLE vehicles                   CASCADE;